version: '3'

services:

  redis:
    image: redis
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  postgresqls:
    image: "postgis/postgis"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: melem
      POSTGRES_PASSWORD: 12345
    networks:
      - mongo-compose-network
    volumes:
      -/usr/database/pg

networks:
  mongo-compose-network:
    driver: bridge
